### ISSUE TITLE
Buffer overflow in Bravais_catalog

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/CaratInterface#18]
Maybe this should be reported in Carat : CC @DominikBernhardt 

The new version is now propagated to Docker container for the stable-4.11 branch, and its test fails: see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/jobs/621170691

The log shows

```
Testing caratinterface 2.3.1, test=/home/gap/inst/gap-stable-4.11/pkg/CaratInterface/tst/testall.g, all packages=false
####### There are 3 classes of groups
####### There are 1 classes of groups
####### There are 3 classes of groups
####### There are 1 classes of groups
*** buffer overflow detected ***: /home/gap/inst/gap-stable-4.11/pkg/CaratInterface/bin/x86_64-pc-linux-gnu-default64-kv7/Bravais_catalog terminated
```
and the test output is

```
testing: /home/gap/inst/gap-stable-4.11/pkg/CaratInterface/tst/carat.tst
########> Diff in /home/gap/inst/gap-stable-4.11/pkg/CaratInterface/tst/carat.\
tst:120
# Input is:
BravaisGroupsCrystalFamily( "4-2;1" );
# Expected output:
[ <matrix group of size 576 with 4 generators>, 
  <matrix group of size 144 with 7 generators>, 
  <matrix group of size 288 with 4 generators>, 
  <matrix group of size 144 with 6 generators> ]
# But found:
Error, Carat program Bravais_catalog failed with error code -1
########
    2276 ms (99 ms GC) and 169MB allocated for carat.tst
-----------------------------------
total      2276 ms (99 ms GC) and 169MB allocated
              1 failures in 1 of 1 files
```

**Comment by gaehler** [comment]
I am puzzled. The same tests for the development version on GitHub pass, and as I can see it, nothing significant has changed in Carat nor in CaratInterface since Release 2.3.1 (except for the documentation). Is there a significant difference between these two tests? The diagnostic messages in the log above seem to be echoed twice - is the test file executed twice, and fails only on the second run? I can't reproduce this problem on my systems, neither with Release 2.3.1, nor with the development version, but this doesn't mean much.

Hmm, it could have to do with the packing and unpacking of the data tables, which contain files with rather problematic names, containing all kinds of punctuation characters, and even quotes. On my linux system, it works though.

By the way: In the [test of all development versions](https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11-devel), also a package /lbfm-rwth/CaratInterface.git is tested, which doesn't exist. This package is still called Carat, and is not a GAP package.

**Comment by alex-konovalov** [comment]
Puzzled too - it passes e.g. in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/jobs/621589792 indeed. 

There are three runs of the test, and the log show that the problem is present in each three of them.

**Comment by alex-konovalov** [comment]
P.S. Did not look at the setup - it that the case that CaratInterface release uses the version of Carat shipped with CaratInterface, while other CI tests use Carat clone from lbfm-rwth?

**Comment by gaehler** [comment]
This is true, but as I mentioned, there is no difference in the **code** of Carat between the bundled and the GitHub versions. Strangely, only the former is affected.

That said, I have spotted a buffer overrun in `Bravais_catalog`, which likely is responsible. A PR fixing it has been filed. @DominikBernhardt It would be good if this could be merged soon, as I can't be sure that there is not still another problem lurking.

@alex-konovalov Do I have to make an official release to get this tested?

**Comment by alex-konovalov** [comment]
@gaehler the buffer overflow explanation sounds plausible. You can watch tests at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/ and make a release if you see them passing. At the moment, they fail with the same symptoms: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/jobs/621984047

**Comment by gaehler** [comment]
@alex-konovalov Well, as discussed above, the crash happens only with the Carat that is bundled with CaratInterface. So, I need to feed an official or inofficial new package file into your testing procedures.

**Comment by DominikBernhardt** [comment]
@alex-konovalov @gaehler Done.

**Comment by gaehler** [comment]
I have made available a new release 2.3.2. We have to see whether this solves the issue.

**Comment by fingolfin** [comment]
It would be good if `carat` also had proper releases; then @gaehler could include the "official" release tarballs from those releases, and we'd also have a version on `carat` which one could reference.

**Comment by fingolfin** [comment]
Anyway: this works now, see <https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/jobs/627233921>, thanks!
